# -- Main Menu --
# The main menu is displayed in the header at the top of the page.

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 20

[[main]]
  name = "About"
  pageRef = "authors/xinzai"
  weight = 30

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/neuqzxy"
  weight = 100


# -- Footer Menu --

#[[footer]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 10

#[[footer]]
#  name = "About"
#  pageRef = "authors/xinzai"
#  weight = 20
